import {
  StructuralNode, FrameElement, AreaElement, Section,
  DEFAULT_RESTRAINTS, NODE_MERGE_TOLERANCE
} from './types';

export class ModelManager {
  private nodes: Map<number, StructuralNode> = new Map();
  private frames: Map<number, FrameElement> = new Map();
  private areas: Map<number, AreaElement> = new Map();
  private sections: Map<number, Section> = new Map();
  private nextNodeId = 1;
  private nextFrameId = 1;
  private nextAreaId = 1;
  private nextSectionId = 1;

  // =================== NODES ===================

  createNode(x: number, y: number, z: number = 0, restraints = DEFAULT_RESTRAINTS): StructuralNode {
    const existing = this.findNodeAt(x, y, z);
    if (existing) return existing;

    const node: StructuralNode = {
      id: this.nextNodeId++,
      x, y, z,
      restraints: { ...restraints },
    };
    this.nodes.set(node.id, node);
    return node;
  }

  findNodeAt(x: number, y: number, z: number = 0): StructuralNode | undefined {
    for (const node of this.nodes.values()) {
      const dist = Math.sqrt(
        (node.x - x) ** 2 + (node.y - y) ** 2 + (node.z - z) ** 2
      );
      if (dist < NODE_MERGE_TOLERANCE) return node;
    }
    return undefined;
  }

  getNode(id: number): StructuralNode | undefined {
    return this.nodes.get(id);
  }

  getAllNodes(): StructuralNode[] {
    return [...this.nodes.values()];
  }

  moveNode(id: number, x: number, y: number, z?: number): boolean {
    const node = this.nodes.get(id);
    if (!node) return false;
    node.x = x;
    node.y = y;
    if (z !== undefined) node.z = z;
    return true;
  }

  setNodeRestraints(id: number, restraints: StructuralNode['restraints']): boolean {
    const node = this.nodes.get(id);
    if (!node) return false;
    node.restraints = { ...restraints };
    return true;
  }

  deleteNode(id: number): boolean {
    for (const frame of this.frames.values()) {
      if (frame.nodeI === id || frame.nodeJ === id) return false;
    }
    for (const area of this.areas.values()) {
      if (area.nodeIds.includes(id)) return false;
    }
    return this.nodes.delete(id);
  }

  // =================== SECTIONS ===================

  createSection(name: string, b: number, h: number, type: "beam" | "column"): Section {
    const section: Section = { id: this.nextSectionId++, name, b, h, type };
    this.sections.set(section.id, section);
    return section;
  }

  getSection(id: number): Section | undefined {
    return this.sections.get(id);
  }

  getAllSections(): Section[] {
    return [...this.sections.values()];
  }

  // =================== FRAME ELEMENTS ===================

  createBeam(nodeIId: number, nodeJId: number, sectionId: number, autoGenerated = false): FrameElement | null {
    if (!this.nodes.has(nodeIId) || !this.nodes.has(nodeJId)) return null;
    for (const f of this.frames.values()) {
      if (f.type === 'beam' &&
        ((f.nodeI === nodeIId && f.nodeJ === nodeJId) ||
         (f.nodeI === nodeJId && f.nodeJ === nodeIId))) {
        return f;
      }
    }
    const section = this.sections.get(sectionId);
    const frame: FrameElement = {
      id: this.nextFrameId++,
      nodeI: nodeIId,
      nodeJ: nodeJId,
      sectionId,
      type: "beam",
      b: section?.b,
      h: section?.h,
      autoGenerated,
    };
    this.frames.set(frame.id, frame);
    return frame;
  }

  createColumn(nodeIId: number, nodeJId: number, sectionId: number, autoGenerated = false): FrameElement | null {
    if (!this.nodes.has(nodeIId) || !this.nodes.has(nodeJId)) return null;
    const section = this.sections.get(sectionId);
    const frame: FrameElement = {
      id: this.nextFrameId++,
      nodeI: nodeIId,
      nodeJ: nodeJId,
      sectionId,
      type: "column",
      b: section?.b,
      h: section?.h,
      autoGenerated,
    };
    this.frames.set(frame.id, frame);
    return frame;
  }

  getFrame(id: number): FrameElement | undefined {
    return this.frames.get(id);
  }

  getAllFrames(): FrameElement[] {
    return [...this.frames.values()];
  }

  getBeams(): FrameElement[] {
    return this.getAllFrames().filter(f => f.type === 'beam');
  }

  getColumns(): FrameElement[] {
    return this.getAllFrames().filter(f => f.type === 'column');
  }

  updateFrameSection(id: number, b: number, h: number): boolean {
    const frame = this.frames.get(id);
    if (!frame) return false;
    frame.b = b;
    frame.h = h;
    return true;
  }

  updateAreaThickness(id: number, thickness: number): boolean {
    const area = this.areas.get(id);
    if (!area) return false;
    area.thickness = thickness;
    return true;
  }

  deleteElement(id: number): boolean {
    return this.frames.delete(id);
  }

  // =================== AREA ELEMENTS ===================

  createArea(nodeIds: number[], thickness: number, autoGenerated = false): AreaElement | null {
    for (const nid of nodeIds) {
      if (!this.nodes.has(nid)) return null;
    }
    const area: AreaElement = {
      id: this.nextAreaId++,
      nodeIds: [...nodeIds],
      thickness,
      autoGenerated,
    };
    this.areas.set(area.id, area);
    return area;
  }

  getArea(id: number): AreaElement | undefined {
    return this.areas.get(id);
  }

  getAllAreas(): AreaElement[] {
    return [...this.areas.values()];
  }

  deleteArea(id: number): boolean {
    return this.areas.delete(id);
  }

  // =================== MODEL OPERATIONS ===================

  clear(): void {
    this.nodes.clear();
    this.frames.clear();
    this.areas.clear();
    this.nextNodeId = 1;
    this.nextFrameId = 1;
    this.nextAreaId = 1;
  }

  clearAutoGenerated(): void {
    for (const [id, frame] of this.frames) {
      if (frame.autoGenerated) this.frames.delete(id);
    }
    for (const [id, area] of this.areas) {
      if (area.autoGenerated) this.areas.delete(id);
    }
    const referencedNodes = new Set<number>();
    for (const f of this.frames.values()) {
      referencedNodes.add(f.nodeI);
      referencedNodes.add(f.nodeJ);
    }
    for (const a of this.areas.values()) {
      a.nodeIds.forEach(id => referencedNodes.add(id));
    }
    for (const [id] of this.nodes) {
      if (!referencedNodes.has(id)) {
        this.nodes.delete(id);
      }
    }
  }

  getStats() {
    return {
      nodes: this.nodes.size,
      beams: this.getBeams().length,
      columns: this.getColumns().length,
      areas: this.areas.size,
    };
  }

  getFrameLength(frame: FrameElement): number {
    const ni = this.nodes.get(frame.nodeI);
    const nj = this.nodes.get(frame.nodeJ);
    if (!ni || !nj) return 0;
    return Math.sqrt((nj.x - ni.x) ** 2 + (nj.y - ni.y) ** 2 + (nj.z - ni.z) ** 2);
  }

  getFrameDirection(frame: FrameElement): 'horizontal' | 'vertical' {
    const ni = this.nodes.get(frame.nodeI);
    const nj = this.nodes.get(frame.nodeJ);
    if (!ni || !nj) return 'horizontal';
    if (Math.abs(nj.z - ni.z) > NODE_MERGE_TOLERANCE) return 'vertical';
    if (Math.abs(nj.y - ni.y) < NODE_MERGE_TOLERANCE) return 'horizontal';
    return 'vertical';
  }
}
