// ===================== STRUCTURAL MODEL CORE TYPES =====================

export interface StructuralNode {
  id: number;
  x: number;
  y: number;
  z: number;
  restraints: {
    ux: boolean;
    uy: boolean;
    uz: boolean;
    rx: boolean;
    ry: boolean;
    rz: boolean;
  };
  label?: string;
}

export interface FrameElement {
  id: number;
  nodeI: number;
  nodeJ: number;
  sectionId: number;
  type: "beam" | "column";
  label?: string;
  b?: number;
  h?: number;
  autoGenerated?: boolean;
}

export interface AreaElement {
  id: number;
  nodeIds: number[];
  thickness: number;
  label?: string;
  autoGenerated?: boolean;
}

export interface Section {
  id: number;
  name: string;
  b: number;
  h: number;
  type: "beam" | "column";
}

export const DEFAULT_RESTRAINTS = {
  ux: false, uy: false, uz: false,
  rx: false, ry: false, rz: false,
};

export const FIXED_RESTRAINTS = {
  ux: true, uy: true, uz: true,
  rx: true, ry: true, rz: true,
};

export const PINNED_RESTRAINTS = {
  ux: true, uy: true, uz: true,
  rx: false, ry: false, rz: false,
};

export const NODE_MERGE_TOLERANCE = 0.001;
