import { ModelManager } from '../model/modelManager';
import { PINNED_RESTRAINTS, StructuralNode, Section } from '../model/types';

export interface SlabInput {
  id: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

/**
 * Generates structural model from slab geometry:
 * 1. Creates nodes at slab corners
 * 2. Creates beams along slab edges
 * 3. Creates columns at nodes (as vertical frame elements)
 * 4. Creates area elements for slabs
 */
export function generateStructureFromSlabs(
  model: ModelManager,
  slabs: SlabInput[],
  beamSection: Section,
  columnSection: Section,
  slabThickness: number,
  columnHeight: number = 4
): {
  nodeMap: Map<string, StructuralNode>;
  slabNodeMap: Map<string, number[]>;
} {
  model.clearAutoGenerated();

  const nodeMap = new Map<string, StructuralNode>();
  const slabNodeMap = new Map<string, number[]>();

  // Step 1: Create nodes at all slab corners
  const cornerPoints = new Set<string>();
  for (const slab of slabs) {
    const corners = [
      { x: slab.x1, y: slab.y1 },
      { x: slab.x2, y: slab.y1 },
      { x: slab.x1, y: slab.y2 },
      { x: slab.x2, y: slab.y2 },
    ];
    for (const p of corners) {
      const key = `${p.x},${p.y}`;
      if (!cornerPoints.has(key)) {
        cornerPoints.add(key);
        const node = model.createNode(p.x, p.y, 0, PINNED_RESTRAINTS);
        nodeMap.set(key, node);
      }
    }
  }

  // Step 2: Create beams along slab edges (avoiding duplicates)
  const edgeSet = new Set<string>();
  for (const slab of slabs) {
    const edges = [
      { x1: slab.x1, y1: slab.y1, x2: slab.x2, y2: slab.y1 },
      { x1: slab.x2, y1: slab.y1, x2: slab.x2, y2: slab.y2 },
      { x1: slab.x1, y1: slab.y2, x2: slab.x2, y2: slab.y2 },
      { x1: slab.x1, y1: slab.y1, x2: slab.x1, y2: slab.y2 },
    ];
    for (const e of edges) {
      const [px1, py1, px2, py2] = e.x1 < e.x2 || (e.x1 === e.x2 && e.y1 < e.y2)
        ? [e.x1, e.y1, e.x2, e.y2] : [e.x2, e.y2, e.x1, e.y1];
      const edgeKey = `${px1},${py1}-${px2},${py2}`;

      if (!edgeSet.has(edgeKey)) {
        edgeSet.add(edgeKey);
        const nodeI = nodeMap.get(`${px1},${py1}`);
        const nodeJ = nodeMap.get(`${px2},${py2}`);
        if (nodeI && nodeJ) {
          model.createBeam(nodeI.id, nodeJ.id, beamSection.id, true);
        }
      }
    }
  }

  // Step 3: Create columns at each node (vertical elements)
  for (const [, node] of nodeMap) {
    const bottomNode = model.createNode(node.x, node.y, -columnHeight, {
      ux: true, uy: true, uz: true,
      rx: true, ry: true, rz: true,
    });
    model.createColumn(bottomNode.id, node.id, columnSection.id, true);
  }

  // Step 4: Create area elements for slabs
  for (const slab of slabs) {
    const n1 = nodeMap.get(`${slab.x1},${slab.y1}`);
    const n2 = nodeMap.get(`${slab.x2},${slab.y1}`);
    const n3 = nodeMap.get(`${slab.x2},${slab.y2}`);
    const n4 = nodeMap.get(`${slab.x1},${slab.y2}`);
    if (n1 && n2 && n3 && n4) {
      model.createArea([n1.id, n2.id, n3.id, n4.id], slabThickness, true);
      slabNodeMap.set(slab.id, [n1.id, n2.id, n3.id, n4.id]);
    }
  }

  return { nodeMap, slabNodeMap };
}
